### PR TITLE
Default initialize maxp members

### PR DESCRIPTION
**Pull request by drott**
Should fix
https://bugs.chromium.org/p/chromium/issues/detail?id=1158774

### CODE REVIEW

**Comment by khaledhosny** [comment]
This is already fixed in 1141c81c411b599e40496679129d0884715e8650. I didn’t do the initialization (though it is safer) as I’d rather the let fuzzer catch this. A proper fix is to reject fonts with maxp version 0 and glyf table or maxp 1 and CFF table.

**Comment by khaledhosny** [comment]
(I can’t see the chromium issue, but I assume it is the same uninitialized memory issue found by oss-fuzz earlier).

**Comment by drott** [comment]
Good, thanks for the explanation, works for me.

**Comment by drott** [comment]
> (I can’t see the chromium issue, but I assume it is the same uninitialized memory issue found by oss-fuzz earlier).

Yes, probably similar. I had one CL where I only used the new maxp sanitization without your follow-up change so that the Chromium fuzzer found this, too.

**Pull request closed without merging**
