### PR TITLE
Do not drop vhea/vmtx when GSUB does not exist

### PR DESCRIPTION
**Pull request by irori**
For context, see http://crbug.com/548124.

### CODE REVIEW

**Comment by khaledhosny** [comment]
CC @jfkthame

**Comment by khaledhosny** [comment]
Some tests will need to be updated as well, see the travis failures.

**Comment by irori** [comment]
Tests updated.

**Comment by khaledhosny** [comment]
@jfkthame is the original issue that required this check still relevant for Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=637481)?

**Comment by behdad** [comment]
> @jfkthame is the original issue that required this check still relevant for Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=637481)?

Reading the issue, it sounds like it's a Windows limitation that we might want to address in OTS, for example by synthesizing a fake GSUB with vrt2 or something...

**Comment by behdad** [comment]
> @jfkthame is the original issue that required this check still relevant for Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=637481)?
> 
> Reading the issue, it sounds like it's a Windows limitation that we might want to address in OTS, for example by synthesizing a fake GSUB with vrt2 or something...

Though, if the font already has GSUB, that will be complicated...

**Comment by behdad** [comment]
Maybe this has been "fixed" in DWrite?

**Comment by khaledhosny** [comment]
It sounds like a GDI-specific issue, but Firefox still support GDI.

**Comment by jfkthame** [comment]
AFAICS from reading the issues, it seems reasonable to make this change. There's no fundamental reason for the presence of vhea/vmtx to be conditional on the presence of GSUB.

I don't think there's any need for OTS to try and do special magic here, like synthesizing a GSUB 'vrt2' feature if the font has vertical metrics but no GSUB. Such a font simply won't work very well on Windows, at least; not our problem.

**Comment by khaledhosny** [comment]
Great. Merged manually.

**Pull request closed without merging**
