### PR TITLE
Add in WOFF/WOFF2 to README

### PR DESCRIPTION
**Pull request by benkiel**

### CODE REVIEW

**Comment by khaledhosny** [comment]
Which one do you want me to merge, this or #103? :)

**Comment by benkiel** [comment]
Sorry, I made these edits quickly on the GitHub web interface, so if I've caused a mess with multiple pulls, let me know and I'll sort it out.

**Comment by khaledhosny** [comment]
Just let me which is the last version, I now have 3 pull requests editing the same file and not sure which to merge.

**Comment by khaledhosny** [comment]
OK, my bad. Different files.

**Comment by benkiel** [comment]
Yes, sorry, not descriptive pull requests. Thank you!

**Pull request merged**
