### PR TITLE
Support external library dependencies

### PR DESCRIPTION
**Pull request by musicinmybrain**
Alternative resolution to #221; see my comments in that issue.

### CODE REVIEW

**Comment by khaledhosny** [comment]
Meson already have built-in support for building dependencies from source if they are not found, so that should be used instead of adding custom options, and distributions already know how to handle it and disable any downloads: https://mesonbuild.com/Subprojects.html

**Review by khaledhosny — CHANGES_REQUESTED** [review]
Meson already have built-in support for building dependencies from source if they are not found, so that should be used instead of adding custom options, and distributions already know how to handle it and disable any downloads: https://mesonbuild.com/Subprojects.html

**Comment by musicinmybrain** [comment]
Does that mean your preferred approach is to migrate the woff2/brotli and lz4 dependencies from git submodules to meson subprojects? (An obvious prerequisite would be adding woff2 to the wrapdb.)

**Comment by khaledhosny** [comment]
Yes, if possible.

**Comment by musicinmybrain** [comment]
All right; thanks for the feedback. I will work on a new PR.

**Pull request closed without merging**
